const data = {
    products: [
        {
            _id: 1,
            name: "adidas slim skirt",
            category: "skirts",
            image: "/images/p1.jpg",
            price: 100,
            countInStock: 6,
            brand: "adidas",
            rating: 4,
            numReviews: 8,
            description: "high quality product"
        },
        {
            _id: 2,
            name: "nike slim skirt",
            category: "skirts",
            image: "/images/p2.jpg",
            price: 120,
            countInStock: 7,
            brand: "nike",
            rating: 4.5,
            numReviews: 10,
            description: "high quality product"
        },
        {
            _id: 3,
            name: "puma slim pants",
            category: "pants",
            image: "/images/p3.jpg",
            price: 80,
            countInStock: 4,
            brand: "puma",
            rating: 4.5,
            numReviews: 12,
            description: "high quality product"
        },
        {
            _id: 4,
            name: "adidas fit pants",
            category: "pants",
            image: "/images/p4.jpg",
            price: 120,
            countInStock: 0,
            brand: "adidas",
            rating: 4.5,
            numReviews: 15,
            description: "high quality product"
        },
        {
            _id: 5,
            name: "adidas slim skirt",
            category: "skirts",
            image: "/images/p1.jpg",
            price: 100,
            countInStock: 3,
            brand: "adidas",
            rating: 4,
            numReviews: 9,
            description: "high quality product"
        },
        {
            _id: 6,
            name: "nike slim skirt",
            category: "skirts",
            image: "/images/p2.jpg",
            price: 120,
            countInStock: 16,
            brand: "nike",
            rating: 0.5,
            numReviews: 6,
            description: "high quality product"
        },
        {
            _id: 7,
            name: "puma slim pants",
            category: "pants",
            image: "/images/p3.jpg",
            price: 80,
            countInStock: 18,
            brand: "puma",
            rating: 5,
            numReviews: 3,
            description: "high quality product"
        },
        {
            _id: 8,
            name: "adidas fit pants",
            category: "pants",
            image: "/images/p4.jpg",
            price: 120,
            countInStock: 20,
            brand: "adidas",
            rating: 3.5,
            numReviews: 17,
            description: "high quality product"
        },
        {
            _id: 9,
            name: "adidas slim skirt",
            category: "skirts",
            image: "/images/p1.jpg",
            price: 100,
            countInStock: 0,
            brand: "adidas",
            rating: 4,
            numReviews: 11,
            description: "high quality product"
        },
        {
            _id: 10,
            name: "nike slim skirt",
            category: "skirts",
            image: "/images/p1.jpg",
            price: 120,
            countInStock: 17,
            brand: "nike",
            rating: 0.5,
            numReviews: 5,
            description: "high quality product"
        },
        {
            _id: 11,
            name: "puma slim pants",
            category: "pants",
            image: "/images/p2.jpg",
            price: 80,
            countInStock: 10,
            brand: "puma",
            rating: 1.5,
            numReviews: 14,
            description: "high quality product"
        },
        {
            _id: 12,
            name: "adidas fit pants",
            category: "pants",
            image: "/images/p3.jpg",
            price: 120,
            countInStock: 8,
            brand: "adidas",
            rating: 2.5,
            numReviews: 19,
            description: "high quality product"
        },
    ],
};

export default data